# This file is autogenerated to run all tests in the context of your Genie app.
# It is not necessary to edit this file.
# To create tests, simply add `.jl` test files in the `test/` folder.
# All `.jl` files in the `test/` folder will be automatically executed by running `$ julia --project runtests.jl`
# If you want to selectively run tests, use `$ julia --project runtests.jl test_file_1 test_file_2`

ENV["GENIE_ENV"] = "test"
push!(LOAD_PATH, abspath(normpath(joinpath("..", "src"))))

cd("..")
using Pkg
Pkg.activate(".")

using Genie
Genie.loadapp()

cd(@__DIR__)
Pkg.activate(".")

# !!! Main.UserApp is configured as an alias for Main.Cqn and you might encounter it in some tests
using Main.Cqn, Test, TestSetExtensions, Logging, SafeTestsets

macro includetests(testarg...)
  if length(testarg) == 0
      tests = []
  elseif length(testarg) == 1
      tests = testarg[1]
  else
      error("@includetests takes zero or one argument")
  end

  rootfile = "$(__source__.file)"
  mod = __module__

  quote
      tests = $tests
      rootfile = $rootfile

      if length(tests) == 0
          tests = readdir(dirname(rootfile))
          tests = filter(f->endswith(f, ".jl") && f!= basename(rootfile), tests)
      else
          tests = map(f->string(f, ".jl"), tests)
      end

      println();

      for test in tests
          print(splitext(test)[1], ": ")
          Base.include($mod, test)
          println()
      end
  end
end

Logging.global_logger(NullLogger())

@testset ExtendedTestSet "Cqn tests" begin
  @includetests ARGS
end
